language: ruby

rvm:
  - "1.9.2"
  - "1.9.3"
  - rbx-19mode

env:
  - RACK_ENV=ci

before_install: 
  - sh -e /etc/init.d/xvfb start
  - echo "Started xvfb..."
  
script:
  - DISPLAY=:99.0 bundle exec rake
